### PR TITLE
Update AppShellAttribute.cs

### PR DESCRIPTION
**Pull request by ZwapKillrath**
Use primary constructor

### CODE REVIEW

**Comment by FlorianRappl** [comment]
Same as for #7.

The question is: Do we benefit from this? I'd keep those files rather conservative to be sure they are pretty much always working.

**Comment by ZwapKillrath** [comment]
The thing is that we cant omit these from our static code analysis via editorconfig. It simply doesnt work. And thinking .net 8 etc. I proposed the change - but of course, then it wont be backwards comp.

**Comment by FlorianRappl** [comment]
Hmm the issue that I see is that somebody else might have other settings. So I wonder if there is an option to hide this on our side / via the SDK.

**Comment by ZwapKillrath** [comment]
Tried:
image
But to no avail...

**Comment by FlorianRappl** [comment]
We could try using

```cs
// <autogenerated />
```

in the beginning

**Comment by FlorianRappl** [comment]
Was added to all files we bring.

**Pull request closed without merging**
